//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FutureStarEntities : DbContext
    {
        public FutureStarEntities()
            : base("name=FutureStarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Answer> Answers { get; set; }
        public DbSet<Content> Contents { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<Level> Levels { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<Question> Questions { get; set; }
        public DbSet<Tag_Items> Tag_Items { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<Task_Items> Task_Items { get; set; }
        public DbSet<Task> Tasks { get; set; }
        public DbSet<User_Projects> User_Projects { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
