//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Tag_Items = new HashSet<Tag_Items>();
            this.Task_Items = new HashSet<Task_Items>();
        }
    
        public int Id { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<int> ItemType { get; set; }
        public Nullable<int> ProjectId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Question Question { get; set; }
        public virtual ICollection<Tag_Items> Tag_Items { get; set; }
        public virtual ICollection<Task_Items> Task_Items { get; set; }
    }
}
