//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level
    {
        public Level()
        {
            this.Tags = new HashSet<Tag>();
            this.User_Projects = new HashSet<User_Projects>();
        }
    
        public int Id { get; set; }
        public string LevelText { get; set; }
        public string Description { get; set; }
        public string LevelGroup { get; set; }
        public Nullable<int> LevelOrder { get; set; }
    
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<User_Projects> User_Projects { get; set; }
    }
}
