//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Answers = new HashSet<Answer>();
            this.Items = new HashSet<Item>();
        }
    
        public int Id { get; set; }
        public string QuestionText { get; set; }
        public Nullable<int> QuestionType { get; set; }
        public Nullable<int> ContentId { get; set; }
        public string CorrectAnswer { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Content Content { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
