//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.Tag_Items = new HashSet<Tag_Items>();
        }
    
        public int Id { get; set; }
        public string TagText { get; set; }
        public Nullable<int> LevelId { get; set; }
        public Nullable<int> ProjectId { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual ICollection<Tag_Items> Tag_Items { get; set; }
    }
}
