//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Items
    {
        public int Id { get; set; }
        public int TaskId { get; set; }
        public int ItemId { get; set; }
        public string UserAnswer { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Task Task { get; set; }
    }
}
