//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.User_Projects = new HashSet<User_Projects>();
        }
    
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string BirthDay { get; set; }
        public string ParentEmail { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public string Token { get; set; }
    
        public virtual ICollection<User_Projects> User_Projects { get; set; }
    }
}
