//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Projects
    {
        public User_Projects()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int UserId { get; set; }
        public int ProjectId { get; set; }
        public int Id { get; set; }
        public Nullable<int> LevelId { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual User User { get; set; }
    }
}
